[package]
name = "pddl-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
# Benchmarking
criterion = "0.4"

# Testing
git2 = { version = "0.16", features = ["vendored-openssl"] }
url = "2.3"
indicatif = "0.17"
tempfile = "3.3"
cached = "0.42"

[profile.release]
lto = "fat"
codegen-units = 1

[profile.test]
lto = "fat"
codegen-units = 1
opt-level = 3

[[bench]]
name = "bench"
harness = false