[package]
name = "pddl-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
profiling = { version = "1.0", features = ["profile-with-puffin"] }
puffin_http = "0.11.0"
simple_logger = "4.0.0"
log = "0.4.17"
puffin = "0.14.1"
indicatif = "0.17"
logos = "0.12"
derive_more = "0.99"
num-traits = "0.2.15"

[dev-dependencies]
# Benchmarking
criterion = "0.4"

# Testing
git2 = { version = "0.17", features = ["vendored-openssl"] }
url = "2.3"
indicatif = "0.17"
tempfile = "3.3"
cached = "0.42"
pretty_env_logger = "0.4.0"

[profile.release]
lto = true
opt-level = 3

[[bench]]
name = "bench"
harness = false
