[package]
name = "pddl-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
# Benchmarking
criterion = "0.4"

# Testing
git2 = "0.16"
url = "2.3"
indicatif = "0.17"
tempfile = "3.3"

[[bench]]
name = "bench"
harness = false