name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup toolchain
      - name: Setup toolchain nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          profile: minimal

      # Check
      - run: cargo +nightly fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup toolchain
      - name: Setup toolchain stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal

      # Check
      - run: cargo clippy -- -D clippy::nursery -D clippy::perf -D clippy::pedantic

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup toolchain
      - name: Setup toolchain stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      # Check
      - run: cargo test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup toolchain
      - name: Setup toolchain stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      # Check
      - run: cargo build --all-targets --release

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup toolchain
      - name: Setup toolchain stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: msrv
          profile: minimal

      # Check
      - run: cargo msrv verify
